### ISSUE TITLE
Add the ability to tag passed 'boxes'

### ISSUE THREAD

**Issue by aladhims** [aladhims/deadviz#2]
It's a nice feature to be able to tag passed boxes with something. 
e.g. the first box is the first day the deadline has passed, it was frustating not focusing on it.

- a box can have multiple tags
- the tags can be displayed on hover or small marks on the box

Feel free to contribute.

**Comment by rene-ph** [comment]
Hi @aladhims I want to take this feature.

**Comment by aladhims** [comment]
Great! I assign this issue to you @rene-ph

**Comment by rene-ph** [comment]
Hi @aladhims,
I want to show you the progress to know if this is the right experience that we want. 
![TestTag](https://user-images.githubusercontent.com/3522527/95031674-d8539600-067c-11eb-8914-6d7140f9ff49.gif)

Let me know what you think. 

And another question is regarding the scope of this feature. 
What is done and what is pending:
- [X] Display a button when the cursor is on the red box
- [X] Make new entries when the users clicks on the tag
- [ ] Save the tags in local storage.  **(1)**
- [ ] Edit current tags.  **(2)**
- [ ] Delete in the state/storage the tags that the user deleted.

**Questions**.
**1)** Right now I'm saving the data using the useState hook, I think we want to have this data available after the user closes the window right?
**2)** Are we going to implement this functionality? I think if the user can delete a tag, that could be enough.  

Thanks!

**Comment by aladhims** [comment]
Hi @rene-ph , thanks for showing me the progress and your concerns.

This is awesome! It looks better on the way you display those tags beneath the box.
Although, I also have a concern when the boxes have more than one-row length, will those tags collide with the boxes on the second row and so on?

Also to answer your questions.
1) It would be better if we save it on the **_chrome sync storage_** too (embed it inside existing data structure), that way users can revisit it wherever and whenever they want. Since we don't save the array of boxes, maybe we can save the tags on its own 2D array. e.g. there are **two passed boxes** and three future boxes, and if the user tagged the **2nd box** with **two tags**, the data structure would be `[[],['tag1', 'tag2']]`
2) I think delete is already more than enough for now

**Comment by rene-ph** [comment]
Hi @aladhims ,
Yes, if there are more boxes on the same row, everything will be break into the next line. I'll make a test to see  how it looks and fix it if needed. 
I'll keep working in your comments about the save ! and enhancements for the delete functionality ( now using the chrome sync storage) 
Thanks!

**Comment by aladhims** [comment]
Hi @rene-ph 
I think having `z-index` and some tweaks on CSS to give those tags a shadow would help it a bit? 
Wonderful! Looking forward to seeing the next iteration! 👍

**Comment by aladhims** [comment]
Also @rene-ph , can you kindly replace the tag component with the one from Ant Design to have a consistent and similar design? https://ant.design/components/tag

But if changing that is not easy, we can stick with what we already have 👍

**Comment by rene-ph** [comment]
Hi @aladhims , I'm using the Tag component from ant.
I created a new custom component that will contain the new logic.
Ok, I'll add shadows like the current boxes 👍

**Comment by aladhims** [comment]
Amazing! Thanks @rene-ph

**Comment by aladhims** [comment]
Solved with https://github.com/aladhims/deadviz/pull/14
