### ISSUE TITLE
Add Item Priority Level

### ISSUE THREAD

**Issue by aladhims** [aladhims/deadviz#4]
It would be nice if there's a priority level for each item, thus every item has a different probabilities of being shown.
Higher priority means higher chance of getting shown in the new tab.

Notes:
- Pinned item will always have the highest priority and the probability of its getting shown is 100%
- If there are multiple items of same priority exist, both of them should have the same distributed chance of getting shown

Feel free to contribute.

**Comment by HeartBeat1608** [comment]
Hey, @aladhims . I want to work on this stuff. But can we have a more in-depth discussion over what the priorities should be and how it should be present to the user ?

*BTW, I'm MERN stack dev and your codebase is on ReactJS so, isn't difficult for me to understand what you went with.*

Awaiting your response. Thanks

**Comment by HeartBeat1608** [comment]
As a prima-facie strategy, all pinned items will have priority of 2, rest all items will have priorities between 0 and 1. We can use gaussian distribution to get the best element data for display (excuse me, my math is a little weak, please). And all elements with priority 2 will be displayed regardless of the distribution.

**Comment by aladhims** [comment]
That sounds great @HeartBeat1608 ! I agree with what you mentioned above, but can we make the priorities more distributed rather than only two levels (0 and 1)? I would say 0-4 would be sufficient as 4 is the pinned item thus 0-3 are for other items. Please bear in mind that currently only 1 pinned item so far. So I think thinking this way would help you solve this easier.

**Comment by HeartBeat1608** [comment]
No, I did not mean just 2 priorities. I meant **between 0 and 1**, that  would be a floating number between 0 and 1, and for pinned items, it will be fixed to 2. So, instead of having fixed 0-4 priorities, we would have probabilities and it'll be easier for us to scale with that. (obviously, people won't have just 4-5 deadlines if this grows)

**Comment by aladhims** [comment]
Oh sorry, I didn't catch that floating number, I thought it would be just two integers number 😄  then that sounds even greater!
I'll assign this issue to you @HeartBeat1608

**Comment by HeartBeat1608** [comment]
Hey @aladhims, How do you want the priorities to be assigned ? Should the user assign a priority through a slide bar or should we assign it ourselves (randomly) ?

**Comment by aladhims** [comment]
@HeartBeat1608 Ideally the users should be able to set the priority by themselves. I would suggest using the slider component from Ant Design so we would have a consistent and similar design. 

PTAL here https://ant.design/components/slider/

**Comment by HeartBeat1608** [comment]
Hey @aladhims , Can we have a discussion over how we would select one item based on priority ? also the visualizer shows only 1 deadline, so if there are multiple pinned items then which one to show ?

**Comment by aladhims** [comment]
@HeartBeat1608  As I said previously:

1. There's no multiple pinned items, so it's only one, if one does exist, always show it.
2. If there are two or more items that has the same level of priority, choose them randomly

I think that's good enough for now. Do you have any other suggestions?

**Comment by HeartBeat1608** [comment]
No, I'm clear on this. Hopefully should finish up in maybe a week or so.

**Comment by aladhims** [comment]
Sure @HeartBeat1608 , thanks for bringing this issue further so we all agree on one clear goal 👍

**Comment by HeartBeat1608** [comment]
I've opened the PR with the updates.

**Comment by aladhims** [comment]
Hi @HeartBeat1608, Thanks for the PR, i have reviewed and commented on it, please take a look on them when you're free 👍

**Comment by aladhims** [comment]
Resolved with https://github.com/aladhims/deadviz/pull/15
