### ISSUE TITLE
Add Linter

### ISSUE THREAD

**Issue by aladhims** [aladhims/deadviz#5]
A project with a nice linter would be awesome. 

Feel free to add any linter that has a wide community and already well-established such as ESLint,

**Comment by peakercope** [comment]
hi @aladhims 
I suggest eslint and airbnb config
If you want I can add it

**Comment by aladhims** [comment]
That sounds great! I'll assign this issue to you @peakercope

**Comment by aladhims** [comment]
Solved https://github.com/aladhims/deadviz/pull/7
