### ISSUE TITLE
Add prop types for Visualizer components

### ISSUE THREAD

**Issue by aladhims** [aladhims/deadviz#8]
Visualizer components have no prop types validation.

Feel free to add it

**Comment by dipanshubhola1009** [comment]
hii @aladhims  could you please explain more about the issue?

**Comment by aladhims** [comment]
Currently, there is no prop-types validation for components on`Popup` section, it would nice to have them in a detailed and complete props

**Comment by nataliepina** [comment]
Could I work on this issue? I am very familiar with PropTypes

**Comment by aladhims** [comment]
Okay, I'll assign it to you since you're already familiar with it @nataliepina 👍

**Comment by phanlyhuynh** [comment]
@aladhims Hi, Can you assign to me? Thanks

**Comment by aladhims** [comment]
Since there's no update from previous assignee, i'll re-assign this to you @phanlyhuynh

**Comment by phanlyhuynh** [comment]
@aladhims I fixed it, https://github.com/aladhims/deadviz/pull/12. Can you check for me? Thanks!!!

**Comment by aladhims** [comment]
solved on https://github.com/aladhims/deadviz/pull/12
